#If data is dtored at pod levels other pods cannot access it, if the pod is deleted data will be lost. This is not ideal for databases,so instead of {} we can use on which part the data will be stored on the node

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo
          image: mongo
          args: ["-dbpath", "/data/db"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db #(This is directory in container where the data will be stored)
      volumes:
        - name: mongo-volume
          hostPath:
            path: /data/mongo-volume #(if running in minikube this will be stored in minikube vm, if running in cloud this will be stored on the node where the pod is running)
