---
# tasks file for common
- import_tasks: java.yml
- name: "install required application"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ applications }}"
- name: Include go installation tasks
  include_tasks: go.yaml
