apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
  - kind: User
    name: john # ← this is the user that will be able to read pods in all namespaces
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: developers # ← this is the group that will be able to read pods in all namespaces
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-reader # ← this is the cluster role that we created in the previous step
  apiGroup: rbac.authorization.k8s.io
