apiVersion: v1
kind: Pod
metadata:
  name: probe-demo
  namespace: default
spec:
  containers:
    - name: myapp
      image: nginx

      # Startup - tcpSocket
      # Runs FIRST before liveness and readiness even begin
      # If this fails → container gets RESTARTED
      # If this succeeds → liveness and readiness probes take over
      startupProbe:
        tcpSocket:
          port: 80 # ← checks if port 80 is open and accepting connections
        initialDelaySeconds: 0 # ← start checking immediately
        periodSeconds: 10 # ← check every 10s
        timeoutSeconds: 3 # ← fail if no response in 3s
        successThreshold: 1 # ← must always be 1 for startup
        failureThreshold: 30 # ← gives app 30*10=300s max to start before restarting

      # Liveness - exec
      # Starts ONLY after startupProbe succeeds
      # If this fails → container gets RESTARTED
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy # ← if file doesn't exist → container restarts
        initialDelaySeconds: 10 # ← wait 10s after startup probe passes
        periodSeconds: 5 # ← check every 5s
        timeoutSeconds: 3 # ← fail if no response in 3s
        successThreshold: 1 # ← must always be 1 for liveness
        failureThreshold: 3 # ← restart after 3 consecutive failures

      # Readiness - httpGet
      # Starts ONLY after startupProbe succeeds
      # If this fails → pod REMOVED from service endpoints (no traffic sent)
      readinessProbe:
        httpGet:
          path: /health # ← hits this HTTP endpoint
          port: 80
          scheme: HTTP
          httpHeaders:
            - name: Custom-Header
              value: health-check
        initialDelaySeconds: 5 # ← wait 5s after startup probe passes
        periodSeconds: 5 # ← check every 5s
        timeoutSeconds: 3 # ← fail if no response in 3s
        successThreshold: 2 # ← must succeed twice in a row to be marked ready
        failureThreshold: 3 # ← remove from endpoints after 3 consecutive failures


# **Order of execution:**

# Container Starts
#       ↓
# startupProbe (TCP port 80)        ← runs first, blocks liveness and readiness
#       ↓ succeeds
# livenessProbe (exec file check)   ← runs every 5s, restarts if fails
# readinessProbe (http /health)     ← runs every 5s, stops traffic if fails

