apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  labels:
    app: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: <YOUR_REGISTRY>/todo-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb-service"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: "root"
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: "password"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "todo"
