apiVersion: v1
kind: ReplicasSet
metadata:
  name: nginx-replica
  namespace: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: team
                operator: In
                values:
                  - analytics
              - key: rank
                operator: Lt #(less than)
                values:
                  - "5"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 40
          preference:
            matchExpressions:
              - key: "team"
                operator: In
                values: ["analytics"]
        - weight: 20
          preference:
            matchExpressions:
              - key: "rank"
                operator: Gt
                values: ["4"]
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
